<?php
$dirtys_messages = [
        'restore_backup' => gettext('No valid config.xml found, attempting last known config restore.'),
        'restore_factory' => gettext('No valid config.xml found, attempting to restore factory config.'),
        'kernel' => gettext('Checksum mismatch for kernel.'),
        'base' => gettext('Checksum mismatch for base system.'),
        'packages' => gettext('Checksum mismatch for packages.')
        ];
