#!/bin/sh

VERSION=v4.13.0.1

if [ "`dmidecode -s baseboard-manufacturer`" != "PC Engines" -o "`dmidecode -s baseboard-product-name | tr '[:upper:]' '[:lower:]'`" != "apu2" -o "`dmidecode -s bios-version`" = "${VERSION}" ]; then
  exit 0
fi
flashrom -w /usr/local/share/apu2/apu2_${VERSION}.rom -p internal:boardmismatch=force
