#!/bin/sh

if [ "`dmidecode -s baseboard-manufacturer`" != "PC Engines" -o "`dmidecode -s baseboard-product-name | tr '[:upper:]' '[:lower:]'`" != "apu2" -o "`dmidecode -s bios-version`" = "v4.13.0.5" ]; then
  exit 0
fi
flashrom -w /usr/local/share/apu2/apu2_v4.13.0.5.rom -p internal:boardmismatch=force
