#!/usr/local/bin/php
<?php
require_once('util.inc');
require_once('config.inc');
require_once('certs.inc');

if (isset($config['ca'])) {
    foreach($config['ca'] as $ca)
    {
        if($ca['descr'] == $ca_name) {
            exit(0);
        }
    }
}

$ca_name = "TING CA";

// generate
print "Generate $ca_name\n";

$ca = ['refid' => uniqid(), 'descr' => $ca_name];
$dn = array(
    'countryName' => 'RU',
    'stateOrProvinceName' => '-',
    'localityName' => '-',
    'organizationName' => '-',
    'commonName' => $ca_name
);
if (!ca_create($ca, 2048, 3650, $dn, "sha256")) {
    print "Error creating certificate\n";
    exit(1);
}

$ca_refid = $ca['refid'];

if (!isset($config['ca'])) {
    $config['ca'] = [];
}

$config['ca'][] = $ca;
write_config();

?>
